BOOTLOADER = caterina
SPLIT_KEYBOARD = yes

BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGB_MATRIX_ENABLE = no
UNICODE_ENABLE = yes
NKRO_ENABLE = yes
ONE_SHOT_ENABLE = no
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
AUTO_SHIFT_ENABLE = no
MOUSEKEY_ENABLE = no
